name: Exercise 3 - Docker Build and Push

# This workflow builds a Docker image and pushes it to GitHub Container Registry
# It only runs on push to main branch (not on PRs)

on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest

    # Required permissions for pushing to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Login to Artifactory npm registry
      - name: Setup npm registry
        run: |
          echo "registry=https://trialsga2025.jfrog.io/artifactory/api/npm/sga-npm/" > .npmrc
          echo "//trialsga2025.jfrog.io/artifactory/api/npm/sga-npm/:_authToken=${{ secrets.ARTIFACTORY_TOKEN }}" >> .npmrc    

      # Standard Node.js workdflow...
      - name: Install dependencies
        run: npm i  # Uses Artifactory for downloads
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Publish package
        if: github.ref == 'refs/heads/main'
        run: npm publish --registry https://trialsga2025.jfrog.io/artifactory/api/npm/sga-npm/