name: Exercise 3 - Docker Build and Push

# This workflow builds a Docker image and pushes it to GitHub Container Registry
# It only runs on push to main branch (not on PRs)

on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest

    # Required permissions for pushing to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to GitHub Container Registry
      - name: setup npm registry
        run: |
          echo "registry=https://trialsga2025.jfrog.io/artifactory/api/npm/sga-npm/" > /.npmrc 
          echo "//trialsga2025.jfrog.io/artifactory/api/npm/sga-npm/:_authToken="${{ secrets.ARTIFACTORY_TOKEN }}"" > /.npmrc

      # Extract metadata for Docker
      - name: Install dependecies
        run: npm install

      - name: Build 
        run: npm run build
      - name: test
        run: npm test

      - name: publish package
        if: github.ref == 'refs/heads/main'
        run: npm publish